### ISSUE TITLE
居然想从头实现Vision Transformer

### ISSUE THREAD

**Issue by wfsg00098** [SmallSquare/COMP6248CW#1]

**Comment by SmallSquare** [comment]
哭哭，这是我们作业😭😭
>For the last few years the International Conference on Representation Learning (ICLR; pronounced “i-clear”) has run a challenge encourgaging researchers to try to reproduce the work presented in papers submitted to the conference. The motivation for this has been as a way of trying to address a larger problem surrounding the lack of reproducability of published results in AI papers. This coursework takes direct inspiration from this challenge.
>
>In this coursework you will form a team and choose a paper submitted to one of the ICLR 2021-2020, or NeurIPS 2021-2020 conferences. You will attempt to reproduce the results of your chosen paper and report back on your findings.

**Comment by wfsg00098** [comment]
你要知道Vision Transformer取得不错的效果的前提，是比传统CNNs大的多的多的数据量

**Comment by SmallSquare** [comment]
我知道Transformer吃数据量，但是作业要求说复现了就行，效果不好没事儿，主要是进行实现或者尝试进一步分析。
